// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StateNationalPks.Models;

namespace StateNationalPks.Migrations
{
    [DbContext(typeof(StateNationalPksContext))]
    partial class StateNationalPksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StateNationalPks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Rating");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Description = "excellent place to visit",
                            ImageUrl = "https://www.themediterraneantraveller.com/wp-content/uploads/2018/11/greece-heraklion-00032.jpg",
                            Name = "RockyMountain National Park",
                            Rating = 4,
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            Description = "A good weekend kayaking outlet in Tigard",
                            ImageUrl = "https://cdn.travelpulse.com/images/65aaedf4-a957-df11-b491-006073e71405/c8f899f1-a4af-4ea3-b5dd-447ebbaeb40e/630x355.jpg",
                            Name = "cooks",
                            Rating = 8,
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 3,
                            Description = " All red rocks",
                            ImageUrl = "https://www.toursbylocals.com/images/guides/46/46460/202027064423775.jpg",
                            Name = "Utah arches park",
                            Rating = 3,
                            Type = "National"
                        });
                });

            modelBuilder.Entity("StateNationalPks.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "test",
                            Username = "Leilani"
                        },
                        new
                        {
                            Id = 2,
                            Password = "test",
                            Username = "Travis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
